[package]
name = "submarine-net"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ipnet.workspace = true
thiserror = "2"
tokio = { version = "1", features = ["process", "fs", "io-util", "time", "rt"] }
tracing = "0.1.44"

[target.'cfg(target_os = "linux")'.dependencies]
futures = "0.3"
libc = "0.2"
rtnetlink = "0.23"

[target."cfg(windows)".dependencies]
windows-service = "0.8"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis", "Win32_Networking_WinSock", "Win32_NetworkManagement_WindowsFilteringPlatform", "Win32_System_Rpc", "Win32_Security", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Threading", "Win32_System_Diagnostics_ToolHelp"] }
