//! DNS configuration. Uses systemd-resolved when `/etc/resolv.conf` points to
//! its stub resolver, otherwise rewrites `/etc/resolv.conf` and keeps a
//! backup that survives a daemon crash or a reboot.

use std::path::{Path, PathBuf};

use crate::{Result, TunnelNetConfig, run};

/// System resolver configuration file.
const RESOLV_CONF: &str = "/etc/resolv.conf";
/// Directory of the backups.
///
/// NB: persistent, NOT /run: a rewritten resolv.conf survives a reboot, so its
/// backup must too. Same directory as the daemon's default data dir.
const BACKUP_DIR: &str = "/var/lib/submarine";
/// Copy of the original resolv.conf when it was a regular file.
const BACKUP_FILE: &str = "/var/lib/submarine/resolv.conf.backup";
/// Target of the original resolv.conf when it was a symlink.
const BACKUP_LINK: &str = "/var/lib/submarine/resolv.conf.link";
/// Address of the systemd-resolved stub resolver.
const RESOLVED_STUB: &str = "127.0.0.53";

/// How the DNS of the tunnel was applied, so it can be undone the same way.
enum Backend {
    /// Per-link settings of systemd-resolved on the tunnel interface `if_name`.
    Resolved { if_name: String },
    /// `/etc/resolv.conf` rewritten, original saved in the backup files.
    ResolvConf,
}

/// Points the system resolver to the tunnel's DNS servers.
pub struct DnsManager {
    // backend in use, if the tunnel's DNS is currently applied
    active: Option<Backend>,
}

impl DnsManager {
    /// Creates a manager with nothing applied.
    pub fn new() -> Self {
        Self { active: None }
    }

    /// Applies the DNS servers and search domains of `cfg`, replacing any previous
    /// configuration. Without DNS servers the system configuration is left alone.
    pub async fn apply(&mut self, cfg: &TunnelNetConfig) -> Result<()> {
        // removal of the previous configuration, including that of a crashed run
        self.reset().await?;
        if cfg.dns_servers.is_empty() {
            return Ok(());
        }

        if uses_resolved().await {
            // per-link servers of systemd-resolved on the tunnel interface
            let servers: Vec<String> = cfg.dns_servers.iter().map(ToString::to_string).collect();
            let mut dns_args = vec!["dns", cfg.if_name.as_str()];
            dns_args.extend(servers.iter().map(String::as_str));
            run("resolvectl", &dns_args).await?;

            // `~.` routes every query to this link, not only the search domains
            let mut domain_args = vec!["domain", cfg.if_name.as_str(), "~."];
            domain_args.extend(cfg.dns_search.iter().map(String::as_str));
            run("resolvectl", &domain_args).await?;
            // the link is also used for names matching no routing domain
            run("resolvectl", &["default-route", &cfg.if_name, "true"]).await?;
            self.active = Some(Backend::Resolved {
                if_name: cfg.if_name.clone(),
            });
        } else {
            // without systemd-resolved: backup of the original file, then rewrite
            backup_resolv_conf().await?;
            tokio::fs::write(RESOLV_CONF, render_resolv_conf(cfg)).await?;
            self.active = Some(Backend::ResolvConf);
        }
        tracing::info!(servers = ?cfg.dns_servers, "dns applied");
        Ok(())
    }

    /// Undoes the configuration applied by [`DnsManager::apply`], restoring
    /// `/etc/resolv.conf` from the backup if there is one.
    pub async fn reset(&mut self) -> Result<()> {
        if let Some(Backend::Resolved { if_name }) = self.active.take() {
            // fails harmlessly if the interface is already gone
            let _ = run("resolvectl", &["revert", &if_name]).await;
        }
        // NB: the backup is ALWAYS checked, it may come from a previous crashed run
        restore_resolv_conf().await
    }
}

impl Default for DnsManager {
    fn default() -> Self {
        Self::new()
    }
}

/// True when `/etc/resolv.conf` points to the systemd-resolved stub resolver.
async fn uses_resolved() -> bool {
    match tokio::fs::read_to_string(RESOLV_CONF).await {
        Ok(content) => nameservers(&content).any(|ns| ns == RESOLVED_STUB),
        Err(_) => false,
    }
}

/// Addresses of the `nameserver` lines of a resolv.conf.
fn nameservers(content: &str) -> impl Iterator<Item = &str> {
    content
        .lines()
        .filter_map(|line| line.trim().strip_prefix("nameserver"))
        .map(str::trim)
}

/// Contents of the resolv.conf written while the tunnel is up.
fn render_resolv_conf(cfg: &TunnelNetConfig) -> String {
    let mut out =
        String::from("# Generated by Submarine VPN. The original is restored on disconnect.\n");
    for server in &cfg.dns_servers {
        out.push_str(&format!("nameserver {server}\n"));
    }
    if !cfg.dns_search.is_empty() {
        out.push_str(&format!("search {}\n", cfg.dns_search.join(" ")));
    }
    out
}

/// Saves the original resolv.conf: the target of a symlink (which is then removed,
/// so the rewrite does not go through it) or a copy of a regular file.
async fn backup_resolv_conf() -> Result<()> {
    // an existing backup holds the pristine original and must NOT be overwritten
    if Path::new(BACKUP_FILE).exists() || Path::new(BACKUP_LINK).exists() {
        return Ok(());
    }
    tokio::fs::create_dir_all(BACKUP_DIR).await?;
    match tokio::fs::read_link(RESOLV_CONF).await {
        Ok(target) => {
            tokio::fs::write(BACKUP_LINK, target.as_os_str().as_encoded_bytes()).await?;
            tokio::fs::remove_file(RESOLV_CONF).await?;
        }
        Err(_) => {
            tokio::fs::copy(RESOLV_CONF, BACKUP_FILE).await?;
        }
    }
    Ok(())
}

/// Puts back the original resolv.conf saved by [`backup_resolv_conf`], if any,
/// and deletes the backup.
async fn restore_resolv_conf() -> Result<()> {
    // a symlink is recreated, a regular file is copied back
    if let Ok(target) = tokio::fs::read(BACKUP_LINK).await {
        let target = PathBuf::from(String::from_utf8_lossy(&target).into_owned());
        let _ = tokio::fs::remove_file(RESOLV_CONF).await;
        tokio::fs::symlink(target, RESOLV_CONF).await?;
        tokio::fs::remove_file(BACKUP_LINK).await?;
        tracing::info!("resolv.conf symlink restored");
    } else if Path::new(BACKUP_FILE).exists() {
        tokio::fs::copy(BACKUP_FILE, RESOLV_CONF).await?;
        tokio::fs::remove_file(BACKUP_FILE).await?;
        tracing::info!("resolv.conf restored");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // only the addresses of the nameserver lines are returned
    #[test]
    fn finds_nameservers() {
        let content = "# comment\nnameserver 127.0.0.53\noptions edns0\nnameserver ::1\n";
        assert_eq!(
            nameservers(content).collect::<Vec<_>>(),
            vec!["127.0.0.53", "::1"]
        );
    }

    // the rendered file holds the tunnel's servers and search domains
    #[test]
    fn renders_resolv_conf() {
        let cfg = TunnelNetConfig {
            if_name: "sub0".into(),
            if_index: 1,
            addresses: vec![],
            allowed_ips: vec![],
            endpoints: vec![],
            dns_servers: vec!["10.0.0.1".parse().unwrap()],
            dns_search: vec!["corp.example".into()],
        };
        let out = render_resolv_conf(&cfg);
        assert!(out.contains("nameserver 10.0.0.1\n"));
        assert!(out.contains("search corp.example\n"));
    }
}
